### ISSUE TITLE
[Feature] 能不能把漫游新版的空降助手加上来

### ISSUE THREAD

**Issue by qwq13514** [sakarie9/BiliRoamingM#10]
### 原因

能不能把漫游X新版的空降助手加上来 我真的很需要这个
![Screenshot_20241101_164003_com vphonegaga titan](https://github.com/user-attachments/assets/39fa3c72-1d3d-40b0-998f-276663cfaacd)
![Screenshot_20241101_164016_com vphonegaga titan](https://github.com/user-attachments/assets/2063c644-4a23-49f8-a9a5-38b163b743f6)
![Screenshot_20241101_164021_com vphonegaga titan](https://github.com/user-attachments/assets/4b410abf-d6e0-48b7-9316-afb2f0bb6f2c)

### 功能简述

详见漫游X新版

### 功能逻辑

详见漫游X新版

### 实现参考

https://github.com/hanydd/BilibiliSponsorBlock

**Comment by sakarie9** [comment]
漫游X的空降助手闭源，没救

**Comment by lingfengyu-dreaming** [comment]
@qwq13514 修复RoamingX的lsp模块已经可以用了，如果真的需要空降助手可以去看看

**Comment by qwq13514** [comment]
> @qwq13514 修复RoamingX的lsp模块已经可以用了，如果真的需要空降助手可以去看看

在哪里下载 给个项目地址

**Comment by lingfengyu-dreaming** [comment]
> 在哪里下载 给个项目地址

kazutoiris/MRGA

**Comment by qwq13514** [comment]
> > 在哪里下载 给个项目地址
> 
> kazutoiris/MRGA

谢谢
