### ISSUE TITLE
[Feature] 新手求助Help

### ISSUE THREAD

**Issue by Tzqqqq** [sakarie9/BiliRoamingM#13]
### 原因

求助，纯新手， 遇到的问题：”下载使用“栏目中—“前往 BiliRoamingM-PreBuilds Release 下载”点击显示404，而”参照 revanced-cli 文档打包 “栏目中，定制版 revanced-cli.jar下载完后是否需要其他操作，“从 releases 下载 integrations.apk 和 patches.jar ”后，“执行终端命令”一步中我是用powershell输入那串代码，显示Error: Unable to access jarfile revanced-cli.jar。综上，是我遇到的BiliRoamingM下载问题。还有就是我想问一下BiliRoamingX是没了嘛，软件说我违规封禁至2077年，多谢！！！！！
![1730717070064](https://github.com/user-attachments/assets/dd426066-31d3-41b7-8564-e179513535ef)

### 功能简述

1

### 功能逻辑

1

**Comment by sakarie9** [comment]
从当前目录执行命令

**Comment by Tzqqqq** [comment]
![image](https://github.com/user-attachments/assets/3af51df8-42c1-4154-9753-c9baf754b7bf)

**Comment by sakarie9** [comment]
换 java11 以及以上版本

**Comment by Tzqqqq** [comment]
啊抱歉哈又有问题了
![089819343bb0e7f7feeb4e763789e68](https://github.com/user-attachments/assets/e0f9471f-2be2-40b7-97aa-6844ca6089f9)
![c3f807740a615655aa9d69b9c3c2be6](https://github.com/user-attachments/assets/f2022e90-20e0-4c00-8174-5c17c1c6f64c)
![06bde4ed6c73f9a36b998e3e0e34af1](https://github.com/user-attachments/assets/5cdc3ce9-76ed-4ddf-8d0d-8ac7601f61b9)

**Comment by Tzqqqq** [comment]
重新试了下....获得了一个名为bilibili-patched-temporary-files的文件夹，里面有唯一一个文件夹为patcher，这个文件夹中有名为apk和patched的文件夹，打开什么也没有，我需要做什么呐     多谢

![1730810293765](https://github.com/user-attachments/assets/834ae39d-e4f7-4d0a-811d-1c6a96010fe6)

**Comment by Tzqqqq** [comment]
这一步卡了40min，是正常的嘛
![1730813178814](https://github.com/user-attachments/assets/177f089c-c194-4ef1-9f47-f9afa081444e)
![d41f88e109585e657dad7aef7e8dab9](https://github.com/user-attachments/assets/3418c2ef-f069-416e-a08e-81350c1f8e61)
