### ISSUE TITLE
[BUG] 编译后的软件，会被华为手机识别为风险软件

### ISSUE THREAD

**Issue by j2wyatt** [sakarie9/BiliRoamingM#14]
### 系统版本

harmonyos

### Android 版本

huawei

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.14.0

### 问题描述

正常编译，安装后使用，时不时的会收到系统的提醒，说是个病毒软件

### 复现步骤

就是华为手机

### 日志

。。。

**Comment by sakarie9** [comment]
你都用第三方修改的、破解过的APP了，他提醒你有风险是病毒是完全没有问题的

**Comment by j2wyatt** [comment]
好吧，我记得跑路之前的版本是没有这个提示的，我以为会有解决办法，谢谢你

**Comment by sakarie9** [comment]
说正经的，你需要自己重新给apk签名
