### ISSUE TITLE
[BUG] packageInfo is null

### ISSUE THREAD

**Issue by Tzqqqq** [sakarie9/BiliRoamingM#15]
### 系统版本

 Xiaomi HyperOS1.0.14.0.UNPCNXM

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.20.0

### 问题描述

安装显示packageInfo is null
![2df1e47da5988a502c29ef5394b4489](https://github.com/user-attachments/assets/99bb5ce5-1fe0-4658-8e9b-34576236c06a)

### 复现步骤

按照操作获得apk文件，后安装

### 日志

无

### 截图或录屏

![2df1e47da5988a502c29ef5394b4489](https://github.com/user-attachments/assets/e7bd2ea5-95af-4c87-a0b6-4356776d7a8e)

**Comment by sakarie9** [comment]
重新签名apk

**Comment by Tzqqqq** [comment]
用的360加固助手
![fabfa6963eafd087036727688a470f5](https://github.com/user-attachments/assets/06f83f12-adf6-4274-822c-fdfe788489f7)

**Comment by Tzqqqq** [comment]
jar 已签名。

警告:
签名者证书为自签名证书。
为 -digestalg 选项指定的 SHA1 算法被视为存在安全风险而且被禁用。
为 -sigalg 选项指定的 MD5withRSA 算法被视为存在安全风险而且被禁用。
检测到 POSIX 文件权限和/或 symlink 属性。这些属性在进行签名时会被忽略，不受该签名的保护。

**Comment by Tzqqqq** [comment]
> 重新签名apk

老师...
